### ISSUE TITLE
【誤植】Go Basics 演習 66 struct

### ISSUE THREAD

**Issue by Hayato07** [bcts369dojo/materials#43]
概要
誤植がありました。
ヒント: 次の公式ドキュメントを読むか 0、 json.Marshal でググってみましょう。
=>
ヒント: 次の公式ドキュメントを読むか 、 json.Marshal でググってみましょう。

https://github.com/bcts369dojo/materials/blob/master/exercises/ex77/golang-basics-ex66.md

**Comment by Hayato07** [comment]
概要
誤植がありました。
ヒント: 次の公式ドキュメントを読むか 0、 json.Marshal でググってみましょう。
=>
ヒント: 次の公式ドキュメントを読むか 、 json.Marshal でググってみましょう。

**Comment by bcts369** [comment]
ご指摘ありがとうございます。
